# application.yml 示例配置
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.182.1:8848

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.alibaba.nacos.client.naming: DEBUG
